MAIN_LEAGUES = [
    {
        "id": 87,
        "key": "laliga",
        "name": "LaLiga",
        "country": "Spain",
        "sourceUrl": "https://www.fotmob.com/leagues/87/overview/laliga",
    },
    {
        "id": 140,
        "key": "laliga2",
        "name": "LaLiga2",
        "country": "Spain",
        "sourceUrl": "https://www.fotmob.com/leagues/140/overview/laliga2",
    },
    {
        "id": 47,
        "key": "premier_league",
        "name": "Premier League",
        "country": "England",
        "sourceUrl": "https://www.fotmob.com/leagues/47/overview/premier-league",
    },
    {
        "id": 48,
        "key": "championship",
        "name": "Championship",
        "country": "England",
        "sourceUrl": "https://www.fotmob.com/leagues/48/overview/championship",
    },
    {
        "id": 55,
        "key": "serie_a",
        "name": "Serie A",
        "country": "Italy",
        "sourceUrl": "https://www.fotmob.com/leagues/55/overview/serie",
    },
    {
        "id": 86,
        "key": "serie_b",
        "name": "Serie B",
        "country": "Italy",
        "sourceUrl": "https://www.fotmob.com/leagues/86/overview/serie-b",
    },
    {
        "id": 54,
        "key": "bundesliga",
        "name": "Bundesliga",
        "country": "Germany",
        "sourceUrl": "https://www.fotmob.com/leagues/54/overview/bundesliga",
    },
    {
        "id": 146,
        "key": "bundesliga_2",
        "name": "2. Bundesliga",
        "country": "Germany",
        "sourceUrl": "https://www.fotmob.com/leagues/146/overview/2-bundesliga",
    },
    {
        "id": 53,
        "key": "ligue_1",
        "name": "Ligue 1",
        "country": "France",
        "sourceUrl": "https://www.fotmob.com/leagues/53/overview/ligue-1",
    },
    {
        "id": 110,
        "key": "ligue_2",
        "name": "Ligue 2",
        "country": "France",
        "sourceUrl": "https://www.fotmob.com/leagues/110/overview/ligue-2",
    },
    {
        "id": 57,
        "key": "eredivisie",
        "name": "Eredivisie",
        "country": "Netherlands",
        "sourceUrl": "https://www.fotmob.com/leagues/57/overview/eredivisie",
    },
    {
        "id": 61,
        "key": "primeira_liga",
        "name": "Primeira Liga",
        "country": "Portugal",
        "sourceUrl": "https://www.fotmob.com/leagues/61/overview/primeira-liga",
    },
    {
        "id": 67,
        "key": "super_lig",
        "name": "Super Lig",
        "country": "Turkey",
        "sourceUrl": "https://www.fotmob.com/leagues/67/overview/super-lig",
    },
    {
        "id": 130,
        "key": "mls",
        "name": "MLS",
        "country": "USA",
        "sourceUrl": "https://www.fotmob.com/leagues/130/overview/mls",
    },
    {
        "id": 230,
        "key": "liga_mx",
        "name": "Liga MX",
        "country": "Mexico",
        "sourceUrl": "https://www.fotmob.com/leagues/230/overview/liga-mx",
    },
]
